Đồ án quản lý nhân sự demo 3/dbmsQLNS/Areas/Admin/Controllers/LuongAdminController.cs
using dbmsQLNS.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace dbmsQLNS.Areas.Admin.Controllers
{
    public class LuongAdminController : Controller
    {
        QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();
        // GET: Admin/LuongAdmin
        public ActionResult Index()
        {
            var list = db.Database.SqlQuery<Luong>("Sp_Luongs_ShowList").ToList();
            return View(list);
        }

        [HttpGet]
        public ActionResult Edit(String id)
        {
            var luong = db.Luongs.Where(n => n.MaNhanVien == id).SingleOrDefault();
            ViewBag.MaChucVuNV = new SelectList(db.ChucVuNhanViens, "MaChucVuNV", "HSPC");
            return View(luong);
        }
        [HttpPost]
        public ActionResult Edit(Luong luong, CapNhatLuong up)
        {
            var l = db.Luongs.Where(n => n.MaNhanVien == luong.MaNhanVien).FirstOrDefault();
            if (l != null)
            {
                //  l.MaNhanVien = luong.MaNhanVien;
                if (int.Parse(up.LuongSauCapNhat.ToString()) != 0)
                {
                    l.LuongToiThieu = up.LuongSauCapNhat;
                }

                l.BHXH = luong.BHXH == null ? 0 : luong.BHXH;
                l.BHYT = luong.BHYT == null ? 0 : luong.BHYT;
                l.BHTN = luong.BHTN == null ? 0 : luong.BHTN;
                //   l.PhuCap = luong.PhuCap;
                l.ThueThuNhap = luong.ThueThuNhap;
                l.HeSoLuong = luong.HeSoLuong;

                //tao table luu lai moi lan cap nhat luong
                CapNhatLuong capNhat = new CapNhatLuong();
                capNhat.NgayCapNhat = DateTime.Now.Date;
                capNhat.MaNhanVien = luong.MaNhanVien;
                capNhat.LuongHienTai = luong.LuongToiThieu;
                capNhat.LuongSauCapNhat = up.LuongSauCapNhat;
                capNhat.BHXH = luong.BHXH;
                capNhat.BHYT = luong.BHYT;
                capNhat.BHTN = luong.BHTN;
                //  capNhat.PhuCap = luong.PhuCap;
                capNhat.ThueThuNhap = luong.ThueThuNhap;
                capNhat.HeSoLuong = luong.HeSoLuong;

                db.CapNhatLuongs.Add(capNhat);
                db.SaveChanges();
                return View(capNhat);
            }
            ViewBag.MaChucVuNV = new SelectList(db.ChucVuNhanViens, "MaChucVuNV", "HSPC", luong.PhuCap);
            return Redirect("/admin/LuongAdmin");
        }
        public ActionResult ThanhToanLuong()
        {
            var luong = db.Luongs.ToList();

            DateTime now = DateTime.Now;
            foreach (var item in luong)
            {
                ChiTietLuong ct = new ChiTietLuong();
                ct.MaChiTietBangLuong = "t" + now.Month.ToString();
                ct.MaNhanVien = item.MaNhanVien;
                var ctl = db.ChiTietLuongs.Where(n => n.MaNhanVien == ct.MaNhanVien).FirstOrDefault();
                //ct.MaChiTietBangLuong = t+dem.ToString();

                double tienthue = 0, phucap = 0;
                double tong = 0;
                item.HeSoLuong = item.HeSoLuong == null ? 0 : item.HeSoLuong;
                ct.LuongCoBan = item.LuongToiThieu * (double)item.HeSoLuong;

                item.BHXH = item.BHXH == null ? 0 : item.BHXH;
                ct.BHXH = item.BHXH * item.LuongToiThieu / 100;

                item.BHYT = item.BHYT == null ? 0 : item.BHYT;
                ct.BHYT = item.BHYT * item.LuongToiThieu / 100;

                item.BHTN = item.BHTN == null ? 0 : item.BHTN;
                ct.BHTN = item.BHTN * item.LuongToiThieu / 100;


                item.PhuCap = item.PhuCap == null ? 0 : item.PhuCap;
                phucap = item.LuongToiThieu * (double)item.PhuCap;
                ct.PhuCap = phucap;


                item.ThueThuNhap = item.ThueThuNhap == null ? 0 : item.ThueThuNhap;
                tienthue = item.LuongToiThieu * (int)item.ThueThuNhap / 100;
                ct.ThueThuNhap = tienthue;

                ct.NgayNhanLuong = DateTime.Now.Date;
                ct.TienThuong = 0;
                ct.TienPhat = 0;
                tong = tong + ct.LuongCoBan - (double)(ct.BHXH + ct.BHYT + ct.BHTN) - (double)ct.ThueThuNhap + (double)ct.PhuCap;
                ct.TongTienLuong = tong.ToString();
                if (ctl == null)
                {
                    db.ChiTietLuongs.Add(ct);
                }
                ViewBag.ok = "thanh toán thành công";
                db.SaveChanges();
            }
            var list = db.Database.SqlQuery<ChiTietLuong>("Sp_ChiTietLuong_ShowList").ToList();
            return View(list);
        }
        public ActionResult XuatFileLuong(String id)
        {
            //var l = db.ChiTietLuongs.Where(n => n.MaChiTietBangLuong == id).ToList();
            var ds = db.ChiTietLuongs.ToList();
            //===================================================
            DataTable dt = new DataTable();
            //Add Datacolumn
            DataColumn workCol = dt.Columns.Add("Mã nhân viên", typeof(String));
            dt.Columns.Add("Lương cơ bản", typeof(String));
            dt.Columns.Add("BHXH", typeof(String));
            dt.Columns.Add("Phụ cấp", typeof(String));
            dt.Columns.Add("Thuế thu nhập", typeof(String));
            dt.Columns.Add("Ngày nhận lương", typeof(String));
            dt.Columns.Add("Thực lãnh", typeof(String));

            //Add in the datarow


            foreach (var item in ds)
            {
                DataRow newRow = dt.NewRow();
                newRow["Mã nhân viên"] = item.MaNhanVien;
                newRow["Lương cơ bản"] = item.LuongCoBan;
                newRow["BHXH"] = item.BHXH;
                newRow["Phụ cấp"] = item.PhuCap;
                newRow["Thuế thu nhập"] = item.ThueThuNhap;
                newRow["Ngày nhận lương"] = item.NgayNhanLuong;
                newRow["Thực lãnh"] = item.TongTienLuong;


                dt.Rows.Add(newRow);
            }

            //====================================================
            var gv = new GridView();
            //gv.DataSource = ds;
            gv.DataSource = dt;
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;

            Response.AddHeader("content-disposition", "attachment; filename=danh-sach-luong.xls");
            Response.ContentType = "application/ms-excel";

            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);

            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return Redirect("/admin/LuongAdmin");
        }
        public ActionResult QuaTrinhLuong(String id)
        {
            var tangluong = db.CapNhatLuongs.Where(n => n.MaNhanVien == id).ToList();
            if (tangluong != null)
            {
                return View(tangluong);
            }
            return Redirect("/admin/QuanLyLuong");
        }
    }
}

Đồ án quản lý nhân sự demo 3/dbmsQLNS/Areas/Admin/Views/LuongAdmin/Edit.cshtml
@model dbmsQLNS.Models.Luong

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}



<div class="left-content">
    <div class="mother-grid-inner">
        <div class="container-fluid">
            <div class="">
                <div class="">
                    <h1 class="page-header">
                        Câp nhật lương nhân viên
                    </h1>
                    <ol class="breadcrumb">
                        <li>
                            <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","HomeAdmin")">Trang chủ</a>
                        </li>
                        <li>
                            <i class="fa fa-money"></i> Cập nhật lương
                        </li>
                    </ol>
                </div>
            </div>
            <div class="btn btn-default">
                @Html.ActionLink("<<Trở về", "Index")
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.MaNhanVien)

                    <div class="form-group">
                        @Html.LabelFor(model => model.LuongToiThieu, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.LuongToiThieu, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.LuongToiThieu, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.HeSoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.HeSoLuong, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.HeSoLuong, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.BHXH, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.BHXH, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.BHXH, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.BHYT, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.BHYT, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.BHYT, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.BHTN, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.BHTN, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.BHTN, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.PhuCap, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PhuCap, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.PhuCap, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ThueThuNhap, "ThuThuNhap(%)", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ThueThuNhap, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ThueThuNhap, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Cập nhật" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }


            <div class="col-sm-4 w3-agileits-crd">

                <div class="card card-contact-list">
                    <div class="agileinfo-cdr">
                        <div class="card-header">
                            <h3>Thông tin</h3>
                        </div>
                        <div class="card-body p-b-20">
                            <p>Hệ số phụ cấp theo chức vụ của họ (Nhân Viên: <a href="#" target="_blank">0</a> - Trưởng bộ môn:  <a href="#" target="_blank">0.25</a> - Phó Phòng:  <a href="#" target="_blank">0.35</a> - Trưởng Phòng:  <a href="#" target="_blank">0.45</a>) </p>
                            <p>Để chỉnh sửa phụ cấp thì bạn phải cập nhật chức vụ <a href="~/Admin/UserAdmin" target="_blank"> tại đây</a></p>
                            <p>BHXH: <a href="#" target="_blank"> 8% so với lương tối thiểu</a></p>
                            <p>BHYT: <a href="#" target="_blank"> 1.5% so với lương tối thiểu</a></p>
                            <p>BHTN: <a href="#" target="_blank"> 1% so với lương tối thiểu</a></p>


                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="copyrights">
        <p class="fa">Những chỉ số trên chỉ là chỉ số tự đặt, có thể không giống như thực tế</p>
    </div>
</div>

Đồ án quản lý nhân sự demo 3/dbmsQLNS/Areas/Admin/Views/LuongAdmin/Index.cshtml
@{
    ViewBag.Title = "Lương nhân viên";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@using dbmsQLNS.Models
@model List<Luong>

<div class="left-content">
    <div class="mother-grid-inner">
        <div class="container-fluid">
            <div class="">
                <div class="">
                    <h1 class="page-header">
                        Lương nhân viên
                    </h1>
                    <ol class="breadcrumb">
                        <li>
                            <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","HomeAdmin")">Trang chủ</a>
                        </li>
                        <li>
                            <i class="fa fa-money"></i> Lương
                        </li>
                    </ol>
                </div>
            </div>

            <div style="margin:10px">

                <a class="btn btn-primary" href="@Url.Action("ThanhToanLuong", "LuongAdmin")">Danh sách nhận lương</a>
                <a class="btn btn-primary" href="@Url.Action("ThanhToanLuong", "LuongAdmin")">Tính lương</a>
            </div>
            <div class="table-responsive">
                <table id="table-taikhoan" class="table  table-striped table-hover table-bordered ">
                    <thead>
                        <tr class="success">
                            <th>Mã nhân viên</th>
                            <th>Lương tối thiểu</th>
                            <th>Hệ số lương</th>
                            <th>Phụ cấp CV</th>
                            <th>Tiền bảo hiểm</th>
                            <th>Thuế (%)</th>
                            <th>Số bảng lương: @Model.Count</th>

                        </tr>
                    </thead>
                    <tbody>
                        @{
                            foreach (var item in Model)
                            {

                                <tr>
                                    <td>@item.MaNhanVien</td>
                                    <td>
                                        @string.Format("{0:#,#}", @item.LuongToiThieu).Replace(",", ",")
                                    </td>
                                    <td>
                                        @item.HeSoLuong
                                    </td>
                                    <td>
                                        @item.PhuCap
                                    </td>
                                    <td>
                                        <table class="table table-bordered">
                                            <tr><th>XH</th><th>YT</th><th>TN</th></tr>
                                            <tr>
                                                <td>@item.BHXH</td>
                                                <td>@item.BHYT</td>
                                                <td>@item.BHTN</td>
                                            </tr>
                                        </table>

                                    </td>
                                    <td>
                                        @string.Format("{0:#,#}", @item.ThueThuNhap).Replace(",", ",")
                                    </td>
                                    <td>
                                        <a class="btn btn-warning" href="@Url.Action("Edit", "LuongAdmin", new { @id = @item.MaNhanVien })"><i class="fa fa-pencil-square-o x5" aria-hidden="true"></i>Sửa</a>
                                        <a class="btn btn-info" href="@Url.Action("ThanhToanMotNhanVien", "LuongAdmin", new { @id = @item.MaNhanVien })">Tính lương</a>
                                        <a class="btn btn-primary" href="@Url.Action("QuaTrinhTangLuong", "LuongAdmin", new  {@id = @item.MaNhanVien })">Quá trình lương</a>

                                    </td>
                                </tr>

                            }

                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Đồ án quản lý nhân sự demo 3/dbmsQLNS/Areas/Admin/Views/LuongAdmin/QuaTrinhLuong.cshtml
@{
    ViewBag.Title = "QuaTrinhLuong";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>QuaTrinhLuong</h2>

Đồ án quản lý nhân sự demo 3/dbmsQLNS/Areas/Admin/Views/LuongAdmin/ThanhToanLuong.cshtml
@model IEnumerable<dbmsQLNS.Models.ChiTietLuong>
@{
    ViewBag.Title = "Danh sách nhận lương";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="left-content">
    <div class="mother-grid-inner">
        <div class="">
            <div class="">
                <h1 class="page-header">
                    Danh sách Lương nhân viên
                </h1>
                <ol class="breadcrumb">
                    <li>
                        <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","HomeAdmin")">Trang chủ</a>
                    </li>
                    <li>
                        <i class="fa fa-money"></i><a href="@Url.Action("index","LuongAdmin")"> Lương</a>
                    </li>
                </ol>
            </div>
        </div>
        <div style="margin:10px">

            <div class="form-group">
                <a class="btn btn-primary" href="@Url.Action("XuatFileLuong", "LuongAdmin", new {@id = "" })"> Xuất file</a>
                @*<select >
                        <option value="t1">Tháng 1</option>
                        <option value="t1">Tháng 1</option>
                        <option value="t2">Tháng 2</option>
                        <option value="t3">Tháng 3</option>
                        <option value="t4">Tháng 4</option>
                        <option value="t5">Tháng 5</option>
                        <option value="t6">Tháng 6</option>
                        <option value="t7">Tháng 7</option>
                        <option value="t8">Tháng 8</option>
                        <option value="t9">Tháng 9</option>
                        <option value="t10">Tháng 10</option>
                        <option value="t11">Tháng 11</option>
                        <option value="t12">Tháng 12</option>
                    </select>*@
            </div>
        </div>

        <div class="table-responsive">
            <table id="table-taikhoan" class="table table-striped table-hover table-bordered ">
                <thead>
                    <tr class="success">
                        <th>
                            Mã nhân viên
                        </th>

                        <th>
                            Lương cơ bản
                        </th>
                        <th>
                            Bảo hiểm
                        </th>
                        <th>
                            Phụ cấp
                        </th>
                        <th>
                            Thuế thu nhập
                        </th>
                        @*<th>
                                Tiền thưởng
                            </th>
                            <th>
                                Tiền phạt
                            </th>*@
                        <th>
                            Ngày nhận lương
                        </th>
                        <th>
                            Thực lãnh
                        </th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.MaNhanVien)
                            </td>

                            <td>
                                @string.Format("{0:#,#}", @item.LuongCoBan).Replace(",", ",")

                            </td>
                            <td>
                                <table class="table table-bordered">
                                    <tr><th>XH</th><th>YT</th><th>TN</th></tr>
                                    <tr>
                                        <td>@string.Format("{0:#,#}", @item.BHXH).Replace(",", ",")</td>
                                        <td>@string.Format("{0:#,#}", @item.BHYT).Replace(",", ",")</td>
                                        <td>@string.Format("{0:#,#}", @item.BHTN).Replace(",", ",")</td>
                                    </tr>
                                </table>
                            </td>
                            <td>
                                @string.Format("{0:#,#}", @item.PhuCap).Replace(",", ",")

                            </td>
                            <td>
                                @string.Format("{0:#,#}", @item.ThueThuNhap).Replace(",", ",")

                            </td>
                            @*<td>
                                    @string.Format("{0:#,#}", @item.TienThuong).Replace(",", ",")

                                </td>
                                <td>

                                    @string.Format("{0:#,#}", @item.TienPhat).Replace(",", ",")
                                </td>*@
                            <td>
                                @String.Format("{0:dd/MM/yyyy}", @item.NgayNhanLuong)
                            </td>
                            <td>
                                @{
                                    var t = int.Parse(item.TongTienLuong);
                                }

                                @String.Format("{0:#,#}", t).Replace(",", ",")
                            </td>

                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
</div>