Đồ án QLCF demo4/webQLCF/Areas/Admin/Controllers/LinkController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model.EF;
using PagedList;

namespace webQLCF.Areas.Admin.Controllers
{
    public class LinkController : Controller
    {
        private webQLCFCode db = new webQLCFCode();

        // GET: Admin/Link
        public ActionResult Index(int? size, int? page)
        {

            // 1. Tạo list pageSize để người dùng có thể chọn xem để phân trang
            // Bạn có thể thêm bớt tùy ý --- dammio.com
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "5", Value = "5" });
            items.Add(new SelectListItem { Text = "10", Value = "10" });
            items.Add(new SelectListItem { Text = "20", Value = "20" });
            items.Add(new SelectListItem { Text = "25", Value = "25" });
            items.Add(new SelectListItem { Text = "50", Value = "50" });
            items.Add(new SelectListItem { Text = "100", Value = "100" });
            items.Add(new SelectListItem { Text = "200", Value = "200" });

            // 1.1. Giữ trạng thái kích thước trang được chọn trên DropDownList
            foreach (var item in items)
            {
                if (item.Value == size.ToString()) item.Selected = true;
            }

            // 1.2. Tạo các biến ViewBag
            ViewBag.size = items; // ViewBag DropDownList
            ViewBag.currentSize = size; // tạo biến kích thước trang hiện tại

            // 2. Nếu page = null thì đặt lại là 1.
            page = page ?? 1; //if (page == null) page = 1;

            // 3. Tạo truy vấn, lưu ý phải sắp xếp theo trường nào đó, ví dụ OrderBy
            // theo LinkID mới có thể phân trang.
            var links = (from l in db.Users
                         select l).OrderBy(x => x.ID);

            // 4. Tạo kích thước trang (pageSize), mặc định là 5.
            int pageSize = (size ?? 5);

            // 4.1 Toán tử ?? trong C# mô tả nếu page khác null thì lấy giá trị page, còn
            // nếu page = null thì lấy giá trị 1 cho biến pageNumber.
            int pageNumber = (page ?? 1);

            // 5. Trả về các Link được phân trang theo kích thước và số trang.
            return View(links.ToPagedList(pageNumber, pageSize));
        }

        // GET: Admin/Link/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Admin/Link/Create
        public ActionResult Create()
        {
            ViewBag.GroupID = new SelectList(db.UserGroups, "ID", "Name");
            return View();
        }

        // POST: Admin/Link/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,UserName,Password,GroupID,Name,Address,Email,Phone,ProvinceID,DistrictID,CreatedDate,CreatedBy,ModifiedDate,ModifiedBy,Status")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.GroupID = new SelectList(db.UserGroups, "ID", "Name", user.GroupID);
            return View(user);
        }

        // GET: Admin/Link/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            ViewBag.GroupID = new SelectList(db.UserGroups, "ID", "Name", user.GroupID);
            return View(user);
        }

        // POST: Admin/Link/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,UserName,Password,GroupID,Name,Address,Email,Phone,ProvinceID,DistrictID,CreatedDate,CreatedBy,ModifiedDate,ModifiedBy,Status")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GroupID = new SelectList(db.UserGroups, "ID", "Name", user.GroupID);
            return View(user);
        }

        // GET: Admin/Link/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Admin/Link/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Đồ án QLCF demo4/webQLCF/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model;
using Model.Dao;
using Model.EF;
using PagedList;
using webQLCF.Areas.Admin.Models;

namespace webQLCF.Areas.Admin.Controllers
{
    public class ProductController : Controller
    {
        private webQLCFCode db = new webQLCFCode();

        // GET: Admin/Product
        public ActionResult Index(int? size, int? page, string searchString)
        {
            // 1. Tạo list pageSize để người dùng có thể chọn xem để phân trang
            // Bạn có thể thêm bớt tùy ý --- dammio.com
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "9", Value = "9" });
            items.Add(new SelectListItem { Text = "20", Value = "20" });
            items.Add(new SelectListItem { Text = "25", Value = "25" });
            items.Add(new SelectListItem { Text = "50", Value = "50" });
            items.Add(new SelectListItem { Text = "100", Value = "100" });
            items.Add(new SelectListItem { Text = "200", Value = "200" });

            // 1.1. Giữ trạng thái kích thước trang được chọn trên DropDownList
            foreach (var item in items)
            {
                if (item.Value == size.ToString()) item.Selected = true;
            }

            // 1.2. Tạo các biến ViewBag
            ViewBag.size = items; // ViewBag DropDownList
            ViewBag.currentSize = size; // tạo biến kích thước trang hiện tại

            // 2. Nếu page = null thì đặt lại là 1.
            page = page ?? 1; //if (page == null) page = 1;

            // 3. Tạo truy vấn, lưu ý phải sắp xếp theo trường nào đó, ví dụ OrderBy
            // theo LinkID mới có thể phân trang.
            var links = (from l in db.Products
                         select l);
            
            // 4. Tạo kích thước trang (pageSize), mặc định là 5.
            int pageSize = (size ?? 9);

            // 4.1 Toán tử ?? trong C# mô tả nếu page khác null thì lấy giá trị page, còn
            // nếu page = null thì lấy giá trị 1 cho biến pageNumber.
            int pageNumber = (page ?? 1);

            // 5. Trả về các Link được phân trang theo kích thước và số trang.
            //var linksS = from l in db.Products
                        //select l;

            if (!String.IsNullOrEmpty(searchString))
            {
                links = links.Where(s => s.Name.Contains(searchString));
            }
            links = links.OrderBy(x => x.ID);
            return View(links.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult ProductDetail(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }

            ViewBag.CategoryID = new SelectList(db.ProductCategories, "ID", "Name", product.CategoryID);
            return View(product);
        }
        // GET: Admin/Product/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Admin/Product/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.ProductCategories, "ID", "Name");
            return View();
        }

        // POST: Admin/Product/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Code,MetaTitle,Description,Image,MoreImages,Price,PromotionPrice,IncludedVAT,Quantity,CategoryID,Detail,Warranty,CreatedDate,CreatedBy,ModifiedDate,ModifiedBy,MetaKeywords,MetaDescriptions,Status,TopHot,ViewCount")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.ProductCategories, "ID", "Name", product.CategoryID);
            return View(product);
        }

        //GET: Admin/Product/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }

            ViewBag.CategoryID = new SelectList(db.ProductCategories, "ID", "Name", product.CategoryID);
            return View(product);
        }

        //// POST: Admin/Product/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "ID,Name,Code,MetaTitle,Description,Image,MoreImages,Price,PromotionPrice,IncludedVAT,Quantity,CategoryID,Detail,Warranty,CreatedDate,CreatedBy,ModifiedDate,ModifiedBy,MetaKeywords,MetaDescriptions,Status,TopHot,ViewCount")] Product product, HttpPostedFileBase HinhAnh)
        //{
        //    //HttpPostedFileBase Image = null;
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(product).State = EntityState.Modified;
        //        if (product.Image != null)
        //        {
        //            HinhAnh.SaveAs(HttpContext.Server.MapPath("~/Content/images/")
        //                                                     + HinhAnh.FileName);
        //            product.Image = HinhAnh.FileName;
        //            //user.Image = userVal.Image;
        //        }
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.CategoryID = new SelectList(db.ProductCategories, "ID", "Name", product.CategoryID);
        //    return View(product);
        //}
        IEnumerable<Product> GetAllProduct()
        {
            using (webQLCFCode db = new webQLCFCode())
            {
                return db.Products.ToList<Product>();
            }

        }
        //public ActionResult Edit(int id = 0)
        //{
        //    Product product = new Product();
        //    if (id != 0)
        //    {
        //        using (webQLCFCode db = new webQLCFCode())
        //        {
        //            product = db.Products.Where(x => x.ID == id).FirstOrDefault<Product>();
        //        }
        //    }
        //    return View(product);
        //}

        [HttpPost]
        public ActionResult Edit(Product product)
        {
            // try
            //{
            if (product.ImageUpload != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(product.ImageUpload.FileName);
                string extension = Path.GetExtension(product.ImageUpload.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                product.Image = "/Assets/client/images/" + fileName;
                product.ImageUpload.SaveAs(Path.Combine(Server.MapPath("/Assets/client/images/"), fileName));
            }
            using (webQLCFCode db = new webQLCFCode())
            {
                if (product.ID == 0)
                {
                    db.Products.Add(product);
                    db.SaveChanges();
                }
                else
                {
                    db.Entry(product).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            
            // return Json(new { success = true, html = GlobalClass.RenderRazorViewToString(this, "ViewAll", GetAllProduct()), message = "Submitted Successfully" }, JsonRequestBehavior.AllowGet);
            //}
            //catch (Exception ex)
            //{

            //    return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            //}
            return View(product);
        }
        // GET: Admin/Product/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }
        [HttpDelete]
        public ActionResult Delete2(int id)
        {
            Product product = db.Products.Find(id);
            new ProductDao().Delete(id);
            return View("Index");
        }
        // POST: Admin/Product/Delete/5
        [HttpPost, ActionName("Delete2")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

Đồ án QLCF demo4/webQLCF/Areas/Admin/Views/Product/Delete.cshtml
@model Model.EF.Product

@{
    ViewBag.Title = "Delete";
    Layout = null;
}

<div class="modal fade" id="deleteModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title">Xác nhận</h4>
            </div>
            <div class="modal-body">
                <h3>Bạn có chắc muốn xóa sản phẩm này</h3>
                <div>
                    <hr />
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>Tiêu đề</th>
                            <td>@Html.DisplayFor(model => model.ID)</td>
                        </tr>
                        <tr>
                            <th>Tác giả</th>
                            <td>@Html.DisplayFor(model => model.Name)</td>
                        </tr>
                    </table>
                </div>
            </div><!-- /.modal-body -->
            <div class="modal-footer">
                @using (Html.BeginForm("Delete", "Product", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-actions no-color text-center">
                        <input type="submit" value="Xóa" class="btn btn-danger" />
                        <button type="button" class="btn btn-default" data-dismiss="modal">Hủy</button>
                    </div>
                }
            </div><!-- /.modal-footer -->
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>
<script>
    $('.delete-link').click(function (e) {
        var a_href = $(this).attr('href'); /* Lấy giá trị của thuộc tính href */
        e.preventDefault(); /* Không thực hiện action mặc định */
        $.ajax({ /* Gửi request lên server */
            url: a_href, /* Nội dung trong Delete.cshtml cụ thể là deleteModal div được server trả về */
            type: 'GET',
            contentType: 'application/json; charset=utf-8',
            success: function (data) { /* Sau khi nhận được giá */
                $('.body-content').prepend(data); /* body-content div (định nghĩa trong _Layout.cshtml) sẽ thêm deleteModal div vào dưới cùng */
                $('#deleteModal').modal('show'); /* Hiển thị deleteModal div dưới kiểu modal */
            }
        });
    })
</script>

Đồ án QLCF demo4/webQLCF/Areas/Admin/Views/Product/Details.cshtml
@model Model.EF.Product

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductCategory.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductCategory.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoreImages)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoreImages)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PromotionPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PromotionPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IncludedVAT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IncludedVAT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Detail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Detail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Warranty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Warranty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaKeywords)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaKeywords)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaDescriptions)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaDescriptions)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TopHot)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TopHot)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ViewCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ViewCount)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Đồ án QLCF demo4/webQLCF/Areas/Admin/Views/Product/Index.cshtml
@model PagedList.IPagedList<Model.EF.Product>
@using PagedList.Mvc;

<!-- Thêm thư viện -->
<!-- Kết thúc-->

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<h2>Danh sách sản phẩm</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@*@using (Html.BeginForm("Index", "Link", FormMethod.Get))
    {
        <p>
            LinkName: @Html.TextBox("SearchString", (string)ViewBag.searchValue) <input type="submit" value="Tìm kiếm" /> <input type="submit" name="Reset" value="Mặc định" />
            @Html.Hidden("page", (object)ViewBag.page)
            @Html.Hidden("sortProperty", (object)ViewBag.sortProperty)
            @Html.Hidden("sortOrder", (object)ViewBag.sortOrder)
            @Html.Hidden("size", (object)ViewBag.pageSize)
        </p>
    }*@

<table class="table">

    <tr>
        @Html.Raw(ViewBag.Headings)
        <th>
            ID
        </th>
        <th>
            Tên Sản Phẩm
        </th>
        <th>
            Mã SP
        </th>
        <th>
            Miêu tả
        </th>
        <th>
            Ảnh
        </th>
        <th>
            Giá
        </th>
        <th>
            CategoryID
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>

                <img src="@item.Image">
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryID)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Chi Tiết", "Details", new { id = item.ID }) |
                <a class="delete-link" href="@Url.Action("Delete", new { id = item.ID })"><span style="color: red">Xóa</span></a>
                @Ajax.ActionLink("Xóa", "Delete2", new { @id =item.ID}, new AjaxOptions
           {
               Confirm = "Bạn có muốn xóa bản ghi này không?",
               OnComplete = "$('#row_" +@item.ID + "').remove()",
               HttpMethod = "Delete",
           })
            </td>
        </tr>
    }

</table>

<!-- Thêm mã phân trang -->
<br />
<div class="row">
    <div class="col-md-6 col-lg-6 col-xs-6 col-sm-6">
        @using (Html.BeginForm("Index", "Product", FormMethod.Get))
        {
            <p>
                Kích thước trang: @Html.DropDownList("size", (List<SelectListItem>)ViewBag.size, new { @onchange = "this.form.submit();" })
            </p>
        }
    </div>
    <div class="col-md-6 col-lg-6 col-xs-6 col-sm-6 text-right">
        Trang: @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
    </div>
</div>

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, size = ViewBag.currentSize }))
<!-- Kết thúc -->
<script>
    $('.delete-link').click(function (e) {
        var a_href = $(this).attr('href'); /* Lấy giá trị của thuộc tính href */
        e.preventDefault(); /* Không thực hiện action mặc định */
        $.ajax({ /* Gửi request lên server */
            url: a_href, /* Nội dung trong Delete.cshtml cụ thể là deleteModal div được server trả về */
            type: 'GET',
            contentType: 'application/json; charset=utf-8',
            success: function (data) { /* Sau khi nhận được giá */
                $('.body-content').prepend(data); /* body-content div (định nghĩa trong _Layout.cshtml) sẽ thêm deleteModal div vào dưới cùng */
                $('#deleteModal').modal('show'); /* Hiển thị deleteModal div dưới kiểu modal */
            }
        });
    })
</script>